//GlycoGlyph created by Akul Y. Mehta
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};var nameid="cfg_name",childglycan={name:"",linkage:"",monosaccharide:"",linknum:0,substituent:"",children:[]};glyd3render=!1;
var trackname=[],tracknum=-1,templates=[{name:"Chitobiose-core",structure:"GlcNAcb1-4GlcNAc",type:"starter",subtype:"N"},{name:"N-core",structure:"Mana1-6(Mana1-3)Manb1-4GlcNAcb1-4GlcNAc",type:"starter",subtype:"N"},{name:"N-core-fuc",structure:"Mana1-6(Mana1-3)Manb1-4GlcNAcb1-4(Fuca1-6)GlcNAc",type:"starter",subtype:"N"},{name:"N-core-bis",structure:"Mana1-6(GlcNAcb1-4)(Mana1-3)Manb1-4GlcNAcb1-4GlcNAc",type:"starter",subtype:"N"},{name:"N-core-bis-fuc",structure:"Mana1-6(GlcNAcb1-4)(Mana1-3)Manb1-4GlcNAcb1-4(Fuca1-6)GlcNAc",
type:"starter",subtype:"N"},{name:"N-core-hyb",structure:"Mana1-6(Mana1-3)Mana1-6(Mana1-3)Manb1-4GlcNAcb1-4GlcNAc",type:"starter",subtype:"N"},{name:"N-core-hyb-fuc",structure:"Mana1-6(Mana1-3)Mana1-6(Mana1-3)Manb1-4GlcNAcb1-4(Fuca1-6)GlcNAc",type:"starter",subtype:"N"},{name:"N-oligoman",structure:"Mana1-2Mana1-6(Mana1-2Mana1-3)Mana1-6(Mana1-2Mana1-2Mana1-3)Manb1-4GlcNAcb1-4GlcNAc",type:"starter",subtype:"N"},{name:"Core-1",structure:"Galb1-3GalNAc",type:"starter",subtype:"O"},{name:"Core-2",structure:"GlcNAcb1-6(Galb1-3)GalNAc",
type:"starter",subtype:"O"},{name:"Core-3",structure:"GlcNAcb1-3GalNAc",type:"starter",subtype:"O"},{name:"Core-4",structure:"GlcNAcb1-6(GlcNAcb1-3)GalNAc",type:"starter",subtype:"O"},{name:"Core-5",structure:"GalNAca1-3GalNAc",type:"starter",subtype:"O"},{name:"Core-6",structure:"GlcNAcb1-6GalNAc",type:"starter",subtype:"O"},{name:"Core-7",structure:"GalNAca1-6GalNAc",type:"starter",subtype:"O"},{name:"Core-8",structure:"Gala1-3GalNAc",type:"starter",subtype:"O"}],terminals=[{name:"Blood Group A",
sequence:"GalNAca1-3(Fuca1-2)Gal",type:"antigen"},{name:"Blood Group B",sequence:"Galb1-3(Fuca1-2)Gal",type:"antigen"},{name:"Blood Group H",sequence:"Fuca1-2Gal",type:"antigen"},{name:"CAD Antigen",sequence:"Neu5Aca2-6(GalNAcb1-4(Neu5Aca2-3)Galb1-3)GalNAc",type:"antigen"},{name:"Forsmann Antigen",sequence:"GalNAca1-3GalNAcb1-3Gal",type:"antigen"},{name:"Galili Antigen",sequence:"Gala1-3Galb1-4GlcNAc",type:"antigen"},{name:"P antigen",sequence:"GalNAcb1-3Gala1-4Galb1-4Glc",type:"antigen"},{name:"Pk antigen",
sequence:"Gala1-4Galb1-4Glc",type:"antigen"},{name:"SDA Antigen",sequence:"GalNAcb1-4(Neu5Aca2-3)Galb1-4GlcNAcb1-3Gal",type:"antigen"},{name:"High Mannose Terminals",sequence:"Mana1-2Man",type:"mannose"},{name:"LacDiNAc",sequence:"GalNAcb1-4GlcNAc",type:"lactosamine"},{name:"Lactosamine",sequence:"Galb1-4GlcNAc",type:"lactosamine"},{name:"Neo-Lactosamine",sequence:"Galb1-3GlcNAc",type:"lactosamine"},{name:"Poly-Lactosamine",sequence:"Galb1-4GlcNAcb1-3Galb1-4GlcNAc",type:"lactosamine"},{name:"Lewis A",
sequence:"Galb1-3(Fuca1-4)GlcNAc",type:"lewis"},{name:"Lewis B",sequence:"Fuca1-2Galb1-3(Fuca1-4)GlcNAc",type:"lewis"},{name:"Lewis C",sequence:"Galb1-3GlcNAc",type:"lewis"},{name:"Lewis D",sequence:"Fuca1-2Galb1-3GlcNAc",type:"lewis"},{name:"Lewis X",sequence:"Galb1-4(Fuca1-3)GlcNAc",type:"lewis"},{name:"Lewis Y",sequence:"Fuca1-2Galb1-4(Fuca1-3)GlcNAc",type:"lewis"}],monos="Glc Man Gal Gul Alt All Tal Ido GlcNAc ManNAc GalNAc GulNAc AltNAc AllNAc TalNAc IdoNAc GlcN ManN GalN GulN AltN AllN TalN IdoN GlcA ManA GalA GulA AltA AllA TalA IdoA Qui Rha 6dGul 6dAlt 6dTal Fuc QuiNAc RhaNAc 6dAltNAc 6dTalNAc FucNAc Oli Tyv Abe Par Dig Col Ara Lyx Xyl Rib Kdn Neu5Ac Neu5Gc Neu Sia Pse Leg Aci 4eLeg Bac LDmanHep Kdo Dha DDmanHep MurNAc MurNGc Mur Api Fru Tag Sor Psi Hex HexN HexNAc".split(" "),
aminoacids="AGILPVFWYDERHKSTCMNQ".split(""),gctMonoList={Hex:{glycoct:"HEX",transform:"",configdefault:""},Glc:{glycoct:"glc-HEX",transform:"",configdefault:"d"},Man:{glycoct:"man-HEX",transform:"",configdefault:"d"},Gal:{glycoct:"gal-HEX",transform:"",configdefault:"d"},Gul:{glycoct:"gul-HEX",transform:"",configdefault:"d"},Alt:{glycoct:"alt-HEX",transform:"",configdefault:"l"},All:{glycoct:"all-HEX",transform:"",configdefault:"d"},Tal:{glycoct:"tal-HEX",transform:"",configdefault:"d"},Ara:{glycoct:"ara-PEN",
transform:"",configdefault:"l"},Lyx:{glycoct:"lyx-PEN",transform:"",configdefault:"d"},Rib:{glycoct:"rib-PEN",transform:"",configdefault:"d"},Bac:{glycoct:"glc-HEX",transform:"|2:d|4:d|6:d",configdefault:"d"},Fuc:{glycoct:"gal-HEX",transform:"-1:5|6:d",configdefault:"l"},HexA:{glycoct:"HEX",transform:"|6:a",configdefault:""},GlcA:{glycoct:"glc-HEX",transform:"-1:5|6:a",configdefault:"d"},ManA:{glycoct:"man-HEX",transform:"-1:5|6:a",configdefault:"d"},GalA:{glycoct:"gal-HEX",transform:"-1:5|6:a",configdefault:"d"},
GulA:{glycoct:"gul-HEX",transform:"-1:5|6:a",configdefault:"d"},AltA:{glycoct:"alt-HEX",transform:"-1:5|6:a",configdefault:"l"},AllA:{glycoct:"all-HEX",transform:"-1:5|6:a",configdefault:"d"},TalA:{glycoct:"tal-HEX",transform:"-1:5|6:a",configdefault:"d"},Qui:{glycoct:"glc-HEX",transform:"-1:5|6:d",configdefault:"d"},dHex:{glycoct:"HEX",transform:"|6:d",configdefault:""},Ido:{glycoct:"ido-HEX",transform:"",configdefault:"l"},IdoA:{glycoct:"ido-HEX",transform:"-1:5|6:a",configdefault:"l"},Pen:{glycoct:"PEN-1:4",
transform:"",configdefault:""},Rha:{glycoct:"man-HEX",transform:"|6:d",configdefault:"l"},SixdAlt:{glycoct:"alt-HEX",transform:"|6:d",configdefault:"l"},SixdTal:{glycoct:"tal-HEX",transform:"|6:d",configdefault:"d"},Xyl:{glycoct:"xyl-PEN",transform:"",configdefault:"d"},ddHex:{glycoct:"HEX",transform:"|2:d|6:d",configdefault:""},Unknown:{glycoct:"unknown",transform:"",configdefault:""},Oli:{glycoct:"PEN",transform:"|3:d|6:d",configdefault:""},Tyv:{glycoct:"ara-HEX",transform:"|3:d|6:d",configdefault:""},
Abe:{glycoct:"dxyl-HEX",transform:"|3:d|6:d",configdefault:""},Par:{glycoct:"rib-HEX",transform:"|3:d|6:d",configdefault:""},Col:{glycoct:"lxyl-HEX",transform:"|3:d|6:d",configdefault:""},Dig:{glycoct:"rib-HEX",transform:"|2:d|6:d",configdefault:"d"},Nonu:{glycoct:"NON",transform:"",configdefault:""},Kdn:{glycoct:"gro-dgal-NON-2:6",transform:"|1:a|2:keto|3:d",configdefault:"d"},Kdo:{glycoct:"man-OCT-2:6",transform:"|1:a|2:keto|3:d",configdefault:"d"},Fru:{glycoct:"ara-HEX-2:5",transform:"|2:keto",
configdefault:"d"},Assigned:{glycoct:"assigned-PEN",transform:"",configdefault:""},LDManHep:{glycoct:"ldmanhep-HEX",transform:"",configdefault:""},DDManHep:{glycoct:"ddmanhep-HEX",transform:"",configdefault:""},Dha:{glycoct:"dha-HEX",transform:"",configdefault:""},Mur:{glycoct:"mur-HEX",transform:"",configdefault:""},Sia:{glycoct:"sia-NON",transform:"",configdefault:""},Api:{glycoct:"api-PEN",transform:"",configdefault:"l"},Tag:{glycoct:"tag-PEN",transform:"",configdefault:"d"},Sor:{glycoct:"sor-PEN",
transform:"",configdefault:"l"},Psi:{glycoct:"psi-PEN",transform:"",configdefault:"d"}},gctSubList={NAcetyl:{glycoct:"n-acetyl"},Amino:{glycoct:"amino"},NGlycolyl:{glycoct:"n-glycolyl"},Methyl:{glycoct:"methyl"},Acetyl:{glycoct:"acetyl"},Sulfate:{glycoct:"sulfate"},Phosphate:{glycoct:"phosphate"},Bromo:{glycoct:"bromo"},Chloro:{glycoct:"chloro"},Ethyl:{glycoct:"ethyl"},Ethanolamine:{glycoct:"ethanolamine"},Fluoro:{glycoct:"fluoro"},Formyl:{glycoct:"formyl"},Hydroxymethyl:{glycoct:"hydroxymethyl"},
Imino:{glycoct:"imino"},RLactate1:{glycoct:"(r)-lactate"},SLactate1:{glycoct:"(s)-lactate"},NAlanine:{glycoct:"n-alanine"},NFormyl:{glycoct:"n-formyl"},NMethyl:{glycoct:"n-methyl"},NSuccinate:{glycoct:"n-succinate"},NSulfate:{glycoct:"n-sulfate"},NTrifluoroacetyl:{glycoct:"n-trifluoroacetyl"},Nitrate:{glycoct:"nitrate"},Pyruvate:{glycoct:"pyruvate"},Thio:{glycoct:"thio"},RPyruvate:{glycoct:"(r)-pyruvate"},SPyruvate:{glycoct:"(s)-pyruvate"},RLactate2:{glycoct:"(r)-lactate2"},SLactate2:{glycoct:"(s)-lactate2"},
Unknown:{glycoct:"unknown"}},commonMonos="Glc Man Gal GlcNAc GalNAc Fuc Neu5Ac Neu5Gc Neu Xyl IdoA GlcA Unknown".split(" "),getUrl=window.location.href.split("/").slice(0,-1).join("/")+"/",svgStyle="",fetchCSS=d3.text(getUrl+"/css/styles.css").then(function(a){svgStyle=a}),svgarr=[],fetchSVG=d3.xml("img/monos.svg").then(function(a){return svgarr=[].map.call(a.querySelectorAll("symbol"),function(a){return{id:a.getAttribute("data-abbr"),viewBox:a.getAttribute("viewBox"),innerhtml:a.innerHTML.replace(/\n|\t/g,
"").trim(),fullname:a.getAttribute("data-shortname")}})});function resetchildglycan(){childglycan={name:"",linkage:"",monosaccharide:"",linknum:0,substituent:"",children:[]};$("#subscheck").empty();$("#monocheck").empty();$("#linkagecheck").empty()}
function addSub(){var a=Array.from(document.querySelectorAll("#subposlist input"));a=a.length&&a.find(function(a){return a.checked}).value;var b=Array.from(document.querySelectorAll("#subtypelist input"));b=b.length&&b.find(function(a){return a.checked}).value;"other"===b&&(b=document.getElementById("substituentother").value);a="["+(a+b)+"]";$("#subscheck").append(a);childglycan.substituent+=a;makechildglycanname()}
function clearSub(){$("#subscheck").empty();childglycan.substituent="";makechildglycanname()}function monoselect(a){if("Unknown"===a&&(a=prompt("Please enter name for the node",""),null==a)){alert("Error: Name for the node was blank - did not add the node");return}childglycan.monosaccharide=a;$("#monocheck").empty().append(a);makechildglycanname()}
function addLinkage(){var a=Array.from(document.querySelectorAll("#orientlist input"));a=a.length&&a.find(function(a){return a.checked}).value;var b=Array.from(document.querySelectorAll("#anoposlist input"));b=b.length&&b.find(function(a){return a.checked}).value;var c=Array.from(document.querySelectorAll("#acclist input"));c=c.length&&c.find(function(a){return a.checked}).value;childglycan.linknum="?"==c?0:+c;a=a+b+"-"+c;$("#linkagecheck").empty().append(a);childglycan.linkage=a;makechildglycanname()}
function makechildglycanname(){childglycan.name=childglycan.substituent+childglycan.monosaccharide+childglycan.linkage}
function addmono(a,b){function c(b){if(b.name===a[g].data.name)if(g<a.length-1){g++;var d=b.children.findIndex(function(b){return b.name===a[g].data.name});c(b.children[d])}else b.children.forEach(function(a){a.linknum==childglycan.linknum&&(h=!0,alert("You are trying to add a node to a position which is occupied. \nTwo nodes cannot have same linkage acceptor position. \nPlease check the linkages."))}),!1===h&&b.children.push(childglycan);return b}if(""==childglycan.monosaccharide)alert("No monosaccharide selected. \n\nPlease select a monosaccharide to add."),
resetchildglycan(),$("#multimode").empty();else{""===childglycan.linkage&&(childglycan.linkage="??-?");var d=document.getElementById(nameid).value;d=JSON.parse(glycantojson(d));var g=0,h=!1;c(d);outputname(d);!1===h&&0==b&&resetchildglycan()}}function outputname(a){a=d3.hierarchy(a);a=sortchildren(a);a=objecttoname(a);tracknames(a);document.getElementById(nameid).value=a;d3glycanstructure(a,"d3glycanstruc");cfgToGlycoCT()}
function addfirstmono(){nameobj=childglycan;if(""===nameobj.linkage){var a=prompt('You have not added any linkage for the first monosaccharide.\n    \nThis will be treated as an open ring. If this is what you desire leave the field below blank and press OK.\n    \nTo indicate a closed ring please type in the linkage information:\n    \nFor example:\n    \n"??" if linkage position is unknown in both anomeric configuratio and position or\n    \n"?1" where 1 indicates the position number and can be replaced with the position you desire.  or\n    \n"b1" where b indicates the anomeric configuration and 1 indicates the position.\n    ',
"");nameobj.linkage=null==a||""==a?"":a}else nameobj.linkage=nameobj.linkage.split(/\-/g)[0];nameobj.name=nameobj.substituent+nameobj.monosaccharide+nameobj.linkage;outputname(nameobj);resetchildglycan()}
function d3glycanstructure(a,b){drawersize=400;!0===glyd3render&&($("#slideout").css("width",drawersize+"px"),$("#slideout").animate({right:"0px"},{queue:!1,duration:500}));var c=glycantojson(a);c=JSON.parse(c);var d=getDepth(c),g=document.getElementById("drawingchoice").value;"fixdrawingarea"===g?height=420:"fixglycansize"===g&&2>=d?height=50*d:"fixglycansize"===g&&10>d?height=50*d:"fixglycansize"===g&&10<=d&&(height=420);var h={size:[260,height],x:function(a){return a.x},y:function(a){return height-
a.y}};"d3glycanstruc"==b&&d3.select("#d3glycanstrucsub"+b).remove();d=d3.select("#"+b).append("div").attr("id","d3glycanstrucsub"+b);"d3glycanstruc"==b&&d.style("position","absolute").style("bottom","10px");d=d3.select("#d3glycanstrucsub"+b).append("svg").attr("id",b+"SVG").attr("width",360).attr("height",height+50+50).append("g").attr("id","glycang").attr("transform","translate(50,50)");var f=document.getElementById("symbolsize").value;g=d3.tree().size(h.size);var e=d3.hierarchy(c);e=g(e);fixfucers(e,
260);c=e.x-130;0!=c&&d3.select("#glycang").attr("transform","translate("+(50-c)+",50)");c=e.descendants().slice(1);d.selectAll(".glyd3link").data(c).enter().append("path").attr("class","glyd3link").attr("d",function(a){return"M"+a.x+","+h.y(a)+"L"+a.parent.x+","+h.y(a.parent)}).attr("stroke-width",2);c=d.selectAll(".node").data(e.descendants()).enter().append("g").attr("transform",function(a){return rotateFuc(a,h)});c.append("use").attr("xlink:href",function(a,b){return drawsymbol(a,b,"glycan")}).attr("x",
-f/2).attr("y",-f/2).attr("height",f).attr("width",f).attr("class","symbol").on("click",function(a){a=e.path(a);var b=Array.from(document.querySelectorAll("#modelist input"));b=b.length&&b.find(function(a){return a.checked}).value;"add"===b?multimode?addmono(a,!0):addmono(a,!1):"replace"===b?multimode?replacemono(a,!0):replacemono(a,!1):"delete"===b&&deletemono(a)}).on("mouseover",function(a){d3.select(this.parentElement).append("circle").attr("class","highlightnode").attr("r",f/2+10).attr("fill",
function(a){a=Array.from(document.querySelectorAll("#modelist input"));a=a.length&&a.find(function(a){return a.checked}).value;if("add"===a)return d3.select(this.parentElement).selectAll(".symbol").classed("addcursor",!0).classed("replacecursor",!1).classed("deletecursor",!1),"#227093";if("replace"===a)return d3.select(this.parentElement).selectAll(".symbol").classed("replacecursor",!0).classed("addcursor",!1).classed("deletecursor",!1),"#FFBA3B";if("delete"===a)return d3.select(this.parentElement).selectAll(".symbol").classed("deletecursor",
!0).classed("addcursor",!1).classed("replacecursor",!1),"#7D1515"}).attr("fill-opacity",.4).lower();$(document).bind("keyup",function(b){"Delete"!=b.originalEvent.key&&"d"!=b.originalEvent.key||$.when($(document).unbind("keyup")).then(function(b){b=e.path(a);deletemono(b)})})}).on("mouseout",function(a){$(document).unbind("keyup");d3.selectAll(".highlightnode").remove()});var k,p,r,l;null!=document.getElementById("linkagevisible")?k=document.getElementById("linkagevisible").checked:k=!0;null!=document.getElementById("linkagerotate")?
p=document.getElementById("linkagerotate").checked:p=!0;null!=document.getElementById("linkageabbr")?r=document.getElementById("linkageabbr").checked:r=!1;null!=document.getElementById("linkFontSize")?l=document.getElementById("linkFontSize").value:l=14;!0===k&&c.append("text").attr("transform",function(a,b){return transformlinkText(a,b,p,l,r,f)}).text(function(a){return linkageText(a,r)}).attr("font-size",l).attr("text-anchor","middle").style("font-family","Arial,Sans");c.append("text").text(function(a){return subText(a)}).attr("font-size",
l).style("font-family","Arial,Sans").attr("x",-l-3).attr("y",3).attr("text-anchor","end")}function getDepth(a){var b=0;a.children&&a.children.forEach(function(a){a=getDepth(a);a>b&&(b=a)});return 1+b}
function fixfucers(a,b){var c=document.getElementById("fucoseopt").value;if("fucoriginal"!==c){var d=a.x;a.each(function(a){if(-1<a.data.name.search("Fuc")&&0!==a.depth){a.parent.children.filter(function(a){return-1===a.data.name.search("Fuc")});a.y=a.parent.y;var h=a.parent.x;"fucout"===c&&(a.x=a.x<d?a.parent.x-b/4:a.x>d?a.parent.x+b/4:a.x==d?a.parent.x<d?a.parent.x-b/4:a.parent.x>d?a.parent.x+b/4:a.parent.x-b/4:a.parent.x-b/4);"fucdown"===c&&(a.x=a.x<a.parent.x?a.parent.x-b/4:a.parent.x+b/4);"fucleft"===
c&&(a.x=a.parent.x-b/4);var f;a.parent.children.forEach(function(a){-1===a.data.name.search("Fuc")&&void 0==f&&(f=a.x-h)});a.parent.children.forEach(function(b,c){-1===b.data.name.search("Fuc")&&b.data.name!==a.parent.data.name&&b.each(function(a){a.x-=f})})}})}}
function transformlinkText(a,b,c,d,g,h){if(0<b){b=180*Math.atan2(a.y-a.parent.y,a.parent.x-a.x)/Math.PI;h=document.getElementById("fucoseopt").value;-1<a.data.name.search("Fuc")&&"fucoriginal"!=h&&0<a.depth&&(b=a.x<a.parent.x?30:150);if("Fuc"==a.data.monosaccharide&&"fucoriginal"!=h)return 45>=b?"translate("+(a.parent.x-a.x-10)/2+","+(a.y-a.parent.y+25)/2+") rotate("+b+")":"translate("+(a.parent.x-a.x+10)/2+","+(a.y-a.parent.y+46)/2+") rotate("+b+")";if(0==c){var f;g?f=2:f=4;switch(!0){case a.x<a.parent.x:return"translate("+
(a.parent.x-a.x-6*d+d*f)/(d/2)+","+(a.y-a.parent.y+5)/2+")";case a.x===a.parent.x:return"translate("+(a.parent.x-a.x+6*d+d*f)/(d/2)+","+(a.y-a.parent.y+5)/2+")";case a.x>a.parent.x:return"translate("+(a.parent.x-a.x+6*d-d*f)/(d/2)+","+(a.y-a.parent.y+5)/2+")"}}return"translate("+(a.parent.x+10-a.x)/2+","+(a.y-a.parent.y)/2+") rotate("+b+")"}return"translate("+h/4+","+h+")"}
function rotateFuc(a,b){if(0===a.depth||"fucoriginal"===document.getElementById("fucoseopt").value||-1===a.data.name.search("Fuc"))return"translate("+b.x(a)+","+b.y(a)+")";a.y+=2;return a.x<a.parent.x?"translate("+b.x(a)+","+b.y(a)+") rotate(-30)":"translate("+b.x(a)+","+b.y(a)+") rotate(30)"}function drawsymbol(a,b,c){if("gp"!==c||0!==b)return a=void 0!=a.data.monosaccharide?a.data.monosaccharide:a.data.name,""!=a?"img/monos.svg#"+a.toLowerCase():"img/monos.svg#unknown"}
function linkageText(a,b){var c=a.data.linkage;return 1==b?c=c.replace(/a(?=[\d\?]\-[\d\?])/g,"\u03b1").replace(/b(?=[\d\?]\-[\d\?])/,"\u03b2").replace(/[\d|\?]\-/g,""):-1<c.search(/[a,b,\?][\d,\?]\-[\d,\?]/)?(-1<c.search(/a[\d,\?]\-[\d,\?]/)?c=c.replace(/a(?=[\d\?]\-[\d\?])/,"\u03b1"):-1<c.search(/b[\d\?]\-[\d\?]/)&&(c=c.replace(/b(?=[\d\?]\-[\d\?])/,"\u03b2")),c.substr(c.indexOf("-")-2)):-1<c.search(/[a,b,\?]\-/)?c.substr(c.indexOf("-")-1):-1<c.search(/[a,b,\?][\d,\?]/)?"a"===c.charAt(c.length-
2)?"\u03b1"+c.charAt(c.length-1):"b"===c.charAt(c.length-2)?"\u03b2"+c.charAt(c.length-1):c:"a"===c?"\u03b1":"b"===c?"\u03b2":c}function subText(a){if(void 0!=a.data.substituent)return a=a.data.substituent,a=a.replace(/\[(?=[0-9a-zA-Z])/g,"").replace(/\](?=[0-9a-zA-Z])/g,",").replace("]","")}
function deletemono(a){function b(c){if(c.name===a[d].data.name)if(d<a.length-2){d++;var h=c.children.findIndex(function(b){return b.name===a[d].data.name});b(c.children[h])}else h=c.children.findIndex(function(b){return b.name===a[d+1].data.name}),c.children.splice(h,1);return c}if(1==a.length)document.getElementById(nameid).value="",$("#d3glycanstruc").empty(),$("#glycoCT").html("");else{var c=document.getElementById(nameid).value;c=JSON.parse(glycantojson(c));var d=0;b(c);outputname(c);resetchildglycan()}}
function getGTCID(){function a(b){return""!=b.monosaccharide?b:a(b.children[0])}var b=[{anomer:"a",name:"alpha"},{anomer:"b",name:"beta"},{anomer:"?",name:"unknown"},{anomer:"",name:"open"}];$("#gtcid").html('\n    <table class="table table-sm">\n      <thead>\n        <tr>\n          <th>Reducing End Type:</th>\n          <th class="alpha" scope="col">&alpha;</th>\n          <th class="beta" scope="col">&beta;</th>\n          <th class="unknown" scope="col">Unknown (?)</th>\n          <th class="open"  scope="col">Open</th>\n        </tr>\n      </thead>\n      <tbody>\n        <tr>\n          <td>GlyTouCan ID:</th>\n          <td class="alpha" id="alphagtcid"></td>\n          <td class="beta" id="betagtcid"></td>\n          <td class="unknown" id="unknowngtcid"></td>\n          <td class="open" id="opengtcid"></td>\n        </tr>\n      </tbody>\n    </table>\n    ');
var c=document.getElementById(nameid).value,d=JSON.parse(glycantojson(c));d=a(d);if(""!==d.monosaccharide)var g=d.anomer;b.forEach(function(a){d.anomer=a.anomer;var c=JSON.stringify(d);c=jsonToGlycoCT(c);c="https://api.glycosmos.org/glycanformatconverter/2.3.2-snapshot/glycoct2wurcs/"+encodeURI(c);$.get(c).done(function(b){void 0===b.id?$("#"+a.name+"gtcid").html("Error"):"no accnumber"===b.id?$("#"+a.name+"gtcid").html("Not Available"):$("#"+a.name+"gtcid").html('<a href="https://glytoucan.org/Structures/Glycans/'+
b.id+'" target="_blank">'+b.id+"</a>")}).fail(function(){alert("Error communicating with GlyTouCan.")}).done(function(){b.filter(function(a){return a.anomer===g}).forEach(function(a){d3.selectAll("."+a.name).classed("table-success",!0)})})})}
function glycantojson(a){a=a.replace(/ /g,"");a=a.replace(/\((?=\d[a-zA-Z]\))/g,"[");a=a.replace(/(\[\d[a-zA-Z])\)/g,"$1]");-1<a.indexOf("GlcN(Gc)")&&(a=a.replace(/GlcN\(Gc\)/,"GlcNGc"));var b=function(a,b){return((a||"").match(b)||[]).length};a=function(a){var c="",g=0,h=0,f=0,e=0;for(i=a.length-1;0<=i;i--){var k=a.charAt(i);var p=a.slice(0,i).lastIndexOf(")");var r=a.slice(0,i).lastIndexOf("(");var l=a.indexOf(")",i+1),t=a.indexOf("(",i+1);")"==k?(g++,h++,c=")"+c,g>f&&(f=g),0<e&&e--,"("==a.charAt(i+
1)&&(c=c.slice(1))):"("==k?(g--,h--,e++,"("==k&&t>l&&r>p?c=")("+c:"("==k&&(-1===p&&-1===r&&1<e?(k=[].concat($jscomp.arrayFromIterable(c.matchAll(/\(/g))),p=[].concat($jscomp.arrayFromIterable(c.matchAll(/\)/g))),c=")"+"(".repeat(p.length-k.length)+c):c=")"+"(".repeat(e)+c)):c=k+c;0==h&&0==g&&(e=f=0)}for(;b(c,/\)/g)!=b(c,/\(/g);)c="("+c;return c}(a);a=a.replace(/\(/g,"{");a=a.replace(/\)/g,"}");a=function(a){a=a.split(/(}|{|-[\d,\?]|-(?=[a-zA-z]))/g).filter(function(a){return""!==a});var b=[];for(i=
0;i<a.length-1;i++)-1<a[i+1].search(/\-[\d,\?]/)?b.push(a[i]+a[i+1]):0>a[i].search(/\-/)&&b.push(a[i]);b.push(a[a.length-1]);return b}(a);return JSON.stringify(a.reduce(function(a,b){var c=a.lastIndexOf("{");if("{"===b)a.push(b);else if("}"===b)a.splice(c,1);else if("-"!==b){var d,f=b.substring(b.lastIndexOf("]")+1,b.length);f!=b&&(d=b.replace(f,""));for(i=0;i<f.length;i++)if(!0===monos.includes(f.substring(0,f.length-i))){var e=f.substring(f.length-i,f.length);var k=+e.substr(-1);var p=f.substring(0,
f.length-i);break}-1<b.search(/Neu5,9Ac/g)&&(p="Neu",d="[5Ac][9Ac]",e=b.replace(/Neu5,9Ac/g,""),k=+e.substr(-1));void 0==e&&(e="");void 0==p&&(p="");void 0==d&&(d="");void 0==k&&(k=0);f=e.charAt(0);/^\d+$/.test(f)&&(f="?");/\-$/.test(e)&&(e=e.replace(/\-$/,""));a.push({name:b,linkage:e,monosaccharide:p,substituent:d,linknum:k,anomer:f,children:a.splice(c+1,a.length-c-1).reverse()})}return a},[])[0],0,4)}
function cfgToGlycoCT(){var a=document.getElementById(nameid).value;""===a?alert("No name typed. Please check Name above."):(a=glycantojson(a),a=jsonToGlycoCT(a).replace(/\n/g,"<br>"),document.getElementById("glycoCT").innerHTML=a)}
function jsonToGlycoCT(a){function b(a,c){c=void 0===c?1:c;var e=a.data,k=e.monosaccharide,l=0,t=g,q=splitSubs(e.substituent).pop(),n="";n=void 0==e.anomer?"x":""===e.anomer||"-"===e.anomer?"o":"?"==e.anomer?"x":e.anomer;var m="";-1<k.indexOf("NAc")?(m=k.split("NAc")[0],q.unshift("NAc"),l++):-1<k.indexOf("NGc")?(m=k.split("NGc")[0],q.unshift("NGc"),l++):"Neu5Ac"===k?(m="Kdn",q.unshift("5Ac"),l++):"Neu5Gc"===k?(m="Kdn",q.unshift("5Gc"),l++):-1<k.indexOf("N")&&gctMonoList.hasOwnProperty(k.replace(/N/g,
""))?(m=k.replace(/N/g,""),q.unshift("N"),l++):m=k;var u=getRingType(k,n);console.log(m);gctMonoList.hasOwnProperty(m)&&(""==gctMonoList[m].transform?(d+=g+"b:"+n+"-"+gctMonoList[m].configdefault+gctMonoList[m].glycoct+"-"+u+gctMonoList[m].transform,"o"===n&&(d+="|1:aldi")):d+=g+"b:"+n+"-"+gctMonoList[m].configdefault+gctMonoList[m].glycoct+gctMonoList[m].transform,d+="\n",g++);""!==e.linkage&&"?"!==e.linkage&&1!=f&&(n=e.linkage,e=n.charAt(n.length-1),n=n.charAt(n.indexOf("-")-1),"?"===e&&(e="x"),
"?"===n&&(n="x"),h+=f+":"+c+"o("+e+"+"+n+")"+t+"d\n",f++);q=q.filter(function(a){return""!==a});q.forEach(function(a){switch(!0){case "NAc"===a:var b=2;a="n-acetyl";break;case "NGc"===a:b=2;a="n-glycolyl";break;case -1<a.indexOf("Ac"):b=a.split(/(?!\d)/g)[0];console.log(b);a="acetyl";"Neu5Ac"===k&&(a="n-acetyl");break;case -1<a.indexOf("Gc"):b=a.split(/(?!\d)/g)[0];a="glycolyl";"Neu5Gc"===k&&(a="n-glycolyl");break;case -1<a.indexOf("Me"):b=a.split(/(?!\d)/g)[0];a="methyl";break;case -1<a.indexOf("N"):b=
2;a="amino";break;case -1<a.indexOf("S"):b=a.split(/(?!\d)/g)[0];a="sulfate";break;case -1<a.indexOf("P"):b=a.split(/(?!\d)/g)[0];a="phospho";break;default:b=a.charAt(0),a=a.split(/(?!\d)/g)[1]}d+=g+"s:"+a+"\n";h+=f+":"+t+"d("+b+"+1)"+g+"n\n";f++;l++;g++});0<a.data.children.length&&a.children.forEach(function(a){return b(a,t)});return a}var c="Hello";a=JSON.parse(a);a=d3.hierarchy(a);var d="RES\n",g=1,h="LIN\n",f=1;b(a);return c=("LIN\n"!==h?d+h:d).trim()}
function splitSubs(a){if(""===b)return[];var b=a.replace(/\[(?=[0-9a-zA-Z])/g,"").replace(/\](?=[0-9a-zA-Z])/g,",").replace("]","");b=b.split(/,/g);"object"===typeof b&&(b=[b]);return b}function getRingType(a,b){if("o"===b)return"0:0";var c="Rib,Api,Ara";var d="Gal,Glc,Man,GalNAc,GlcNAc,ManNAc,Fuc,Neu5Ac,Neu5Gc,Neu,Sia,Xyl,IdoA,GlcA,\n  GalA,GlcA,ManA,GlcN,GalN,ManN,Hex,HexNAc,HexA,HexN\n  ".split(/,/g);c=c.split(/,/g);return d.includes(a)?"1:5":c.includes(a)?"1:4":"x:x"}
function copyGlycoCT(a){if(document.selection){var b=document.body.createTextRange();b.moveToElementText(document.getElementById(a));b.select().createTextRange();document.execCommand("copy")}else window.getSelection&&(b=document.createRange(),b.selectNode(document.getElementById(a)),window.getSelection().addRange(b),document.execCommand("copy"),alert("GlycoCT Copied"))}
fetchSVG.then(function(a){svgarr.forEach(function(a){appendButton(a,"fulllist")});commonMonos.forEach(function(a){var b=svgarr.find(function(b){return b.id==a});appendButton(b,"commonlist")})});
function appendButton(a,b){var c=d3.select("#"+b).append("div").attr("class","monodiv").append("div").attr("id",b+"btn"+a.id).attr("class","monobtndiv").attr("title",a.id+" OR "+a.fullname).attr("data-abbr",a.id).on("mouseup",function(){monoselect(this.dataset.abbr)}).append("svg").attr("id","mono"+a.id).attr("viewBox",a.viewBox).attr("xmlns","http://www.w3.org/2000/svg").attr("width","55").attr("height","35");c.append("g").attr("transform","scale(0.5 0.5) translate(25,0)").html(a.innerhtml);c.append("g").attr("transform",
"translate(50%,50)").append("text").text(a.id).attr("text-anchor","middle").attr("x","50%").attr("y","90%").attr("font-size","1em")}function appendTerminals(){terminals.forEach(function(a,b){$("#terminalslist").append('\n    <li class="template">\n    <button class="btn btn-outline-primary btn-sm"\n      onclick="addTerminaltoChild('+b+')">'+a.name+"</button>\n    </li>\n  ")})}
function addTerminaltoChild(a){a=terminals[a].sequence;childglycan=JSON.parse(glycantojson(a));$("#monocheck").html(a);$("#linkagecheck").html("<i>Add Linkage</i>")}var bracketcount=0;
function objecttoname(a,b){var c="";if(""!=a.data.monosaccharide&&""!=a.data.linkage){if(void 0===a.data.substituent||"[]"===a.data.substituent)a.data.substituent="";-1===a.data.linkage.search("-")&&0<a.depth&&(a.data.linkage+="-");c=a.data.substituent+a.data.monosaccharide+a.data.linkage+c}else c=""==a.data.linkage&&null==a.parent?a.data.name+c:a.data.name+"-"+c;1<b&&(c+=")");0<a.data.children.length&&a.children.forEach(function(b,g){c=objecttoname(b,a.children.length-g)+c});1<b&&(c="("+c);return c}
function replacemono(a,b){function c(b){if(b.name===a[g].data.name)if(g<a.length-2){g++;var d=b.children.findIndex(function(b){return b.name===a[g].data.name});c(b.children[d])}else{d=b.children.findIndex(function(b){return b.name===a[g+1].data.name});if(""!=childglycan.linkage){var e=b.children.findIndex(function(a){return a.linknum===childglycan.linknum});if(-1<e&&e!=d){alert("Two nodes cannot have same linkage position. Please check linkages.");return}b.children[d].linkage=childglycan.linkage;
b.children[d].linknum=childglycan.linknum}""!=childglycan.monosaccharide&&(b.children[d].monosaccharide=childglycan.monosaccharide);""!=childglycan.substituent?b.children[d].substituent=childglycan.substituent:"[]"==childglycan.substituent&&(b.children[d].substituent="");b.children[d].name=b.children[d].substituent+b.children[d].monosaccharide+b.children[d].linkage}return b}if(1==a.length)document.getElementById(nameid).value="",$("#d3glycanstruc").empty();else if(""==childglycan.monosaccharide&&
""==childglycan.linkage&&""==childglycan.substituent)alert("No replacement criteria selected. Please select what would you like to replace with.");else{var d=document.getElementById(nameid).value;d=JSON.parse(glycantojson(d));var g=0;c(d);outputname(d);!1===b&&resetchildglycan()}}
function replacecss(a){svgStyle.replace(/\/\*.*\*\//g,"").replace(/\r?\n|\r/g,"").split("}").forEach(function(b){if(""!=b.trim()){b=b.split("{");var c=b[0].trim();b[1].split(";").forEach(function(b){if(""!=b.trim()){b=b.split(":");var d=b[0].trim(),h=b[1].trim();"font-weight"==d?d3.select("#"+a).selectAll(c).each(function(a,b){this.getAttribute(d)||this.style[d]===h||d3.select(this).style(d+"",h+"")}):d3.select("#"+a).selectAll(c).each(function(a,b){this.getAttribute(d)||this.style[d]||d3.select(this).style(d+
"",h+"")})}})}})}function replaceuse(a){$("#"+a+" use").each(function(a){a=this.getAttribute("href");if(null!==a){var b=a.split("#")[1],d=this.getAttribute("x"),g=this.getAttribute("y"),h=this.getAttribute("height"),f=this.getAttribute("width");a=svgarr.find(function(a){return a.id.toLowerCase()==b});d='<svg id="'+b+'" x="'+d+'" y="'+g+'" height="'+h+'" width="'+f+'" viewBox="'+a.viewBox+'">';d+=a.innerhtml;d+="</svg>";$(this).parent().prepend(d)}}).remove()}
function savesvg(a){replacecss(a);replaceuse(a);var b=document.getElementById(a);b.setAttribute("xmlns","http://www.w3.org/2000/svg");b.setAttribute("xmlns:xlink","http://www.w3.org/1999/xlink");b=document.getElementById(a).outerHTML;a=new Blob([b],{type:"image/svg+xml;charset=utf-8"});a=URL.createObjectURL(a);b=document.createElement("a");b.href=a;b.download="Figure.svg";document.body.appendChild(b);b.click();document.body.removeChild(b);d3glycanstructure(document.getElementById(nameid).value,"d3glycanstruc")}
function sortchildren(a){0<a.data.children.length&&(a.children.sort(function(a,c){return d3.ascending(a.data.linknum,c.data.linknum)}),-1<a.children.findIndex(function(a){return"Fuc"==a.data.monosaccharide})&&1>=a.depth&&"GlcNAc"===a.data.monosaccharide&&-1<a.children.findIndex(function(a){return"GlcNAc"==a.data.monosaccharide})&&a.children.sort(function(a,c){return"Fuc"==a.data.monosaccharide?-1:"Fuc"==c.data.monosaccharide?1:0}),a.children.forEach(function(a){sortchildren(a)}));return a}
function starttemplate(a){var b=document.getElementById(nameid);if(""==b.value||confirm("This will clear current Name field. Are you sure you would like to continue?")){b.value="";var c=templates.filter(function(b){return b.name==a&&"starter"===b.type});b.value=c[0].structure;tracknames(b.value);d3glycanstructure(b.value,"d3glycanstruc");cfgToGlycoCT()}}
function tracknames(a){0<tracknum&&$("#undodiv").removeClass("hide").addClass("show");trackname[tracknum]=a;tracknum++;trackname=trackname.filter(function(a,c){return c<tracknum});tracknum===trackname.length&&$("#redodiv").addClass("hide").removeClass("show")}
function undo(){if(!(2>tracknum)){var a=document.getElementById(nameid);tracknum--;void 0!=trackname[tracknum-1]&&(a.value=trackname[tracknum-1],""!=a.value?d3glycanstructure(a.value,"d3glycanstruc"):$("#d3glycanstruc").empty());1===tracknum&&$("#undodiv").addClass("hide").removeClass("show");tracknum<trackname.length&&$("#redodiv").removeClass("hide").addClass("show")}}
function redo(){if(!(tracknum>=trackname.length)){var a=document.getElementById(nameid);tracknum++;tracknum<=trackname.length&&(a.value=trackname[tracknum-1],""!=a.value?d3glycanstructure(a.value,"d3glycanstruc"):$("#d3glycanstruc").empty());tracknum===trackname.length&&$("#redodiv").addClass("hide").removeClass("show");tracknum<trackname.length&&$("#undodiv").removeClass("hide").addClass("show")}};