//GlycoGlyph created by Akul Y. Mehta
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,c){a.raw=c;return a};var nameid="cfg_name",childglycan={name:"",linkage:"",monosaccharide:"",linknum:0,substituent:"",children:[]};glyd3render=!1;
var trackname=[],tracknum=-1,templates=[{name:"Chitobiose-core",structure:"GlcNAcb1-4GlcNAc",type:"starter",subtype:"N"},{name:"N-core",structure:"Mana1-6(Mana1-3)Manb1-4GlcNAcb1-4GlcNAc",type:"starter",subtype:"N"},{name:"N-core-fuc",structure:"Mana1-6(Mana1-3)Manb1-4GlcNAcb1-4(Fuca1-6)GlcNAc",type:"starter",subtype:"N"},{name:"N-core-bis",structure:"Mana1-6(GlcNAcb1-4)(Mana1-3)Manb1-4GlcNAcb1-4GlcNAc",type:"starter",subtype:"N"},{name:"N-core-bis-fuc",structure:"Mana1-6(GlcNAcb1-4)(Mana1-3)Manb1-4GlcNAcb1-4(Fuca1-6)GlcNAc",
type:"starter",subtype:"N"},{name:"N-core-hyb",structure:"Mana1-6(Mana1-3)Mana1-6(Mana1-3)Manb1-4GlcNAcb1-4GlcNAc",type:"starter",subtype:"N"},{name:"N-core-hyb-fuc",structure:"Mana1-6(Mana1-3)Mana1-6(Mana1-3)Manb1-4GlcNAcb1-4(Fuca1-6)GlcNAc",type:"starter",subtype:"N"},{name:"N-oligoman",structure:"Mana1-2Mana1-6(Mana1-2Mana1-3)Mana1-6(Mana1-2Mana1-2Mana1-3)Manb1-4GlcNAcb1-4GlcNAc",type:"starter",subtype:"N"},{name:"Core-1",structure:"Galb1-3GalNAc",type:"starter",subtype:"O"},{name:"Core-2",structure:"GlcNAcb1-6(Galb1-3)GalNAc",
type:"starter",subtype:"O"},{name:"Core-3",structure:"GlcNAcb1-3GalNAc",type:"starter",subtype:"O"},{name:"Core-4",structure:"GlcNAcb1-6(GlcNAcb1-3)GalNAc",type:"starter",subtype:"O"},{name:"Core-5",structure:"GalNAca1-3GalNAc",type:"starter",subtype:"O"},{name:"Core-6",structure:"GlcNAcb1-6GalNAc",type:"starter",subtype:"O"},{name:"Core-7",structure:"GalNAca1-6GalNAc",type:"starter",subtype:"O"},{name:"Core-8",structure:"Gala1-3GalNAc",type:"starter",subtype:"O"}],terminals=[{name:"Blood Group A",
sequence:"GalNAca1-3(Fuca1-2)Gal",type:"antigen"},{name:"Blood Group B",sequence:"Galb1-3(Fuca1-2)Gal",type:"antigen"},{name:"Blood Group H",sequence:"Fuca1-2Gal",type:"antigen"},{name:"CAD Antigen",sequence:"Neu5Aca2-6(GalNAcb1-4(Neu5Aca2-3)Galb1-3)GalNAc",type:"antigen"},{name:"Forsmann Antigen",sequence:"GalNAca1-3GalNAcb1-3Gal",type:"antigen"},{name:"Galili Antigen",sequence:"Gala1-3Galb1-4GlcNAc",type:"antigen"},{name:"P antigen",sequence:"GalNAcb1-3Gala1-4Galb1-4Glc",type:"antigen"},{name:"Pk antigen",
sequence:"Gala1-4Galb1-4Glc",type:"antigen"},{name:"SDA Antigen",sequence:"GalNAcb1-4(Neu5Aca2-3)Galb1-4GlcNAcb1-3Gal",type:"antigen"},{name:"High Mannose Terminals",sequence:"Mana1-2Man",type:"mannose"},{name:"LacDiNAc",sequence:"GalNAcb1-4GlcNAc",type:"lactosamine"},{name:"Lactosamine",sequence:"Galb1-4GlcNAc",type:"lactosamine"},{name:"Neo-Lactosamine",sequence:"Galb1-3GlcNAc",type:"lactosamine"},{name:"Poly-Lactosamine",sequence:"Galb1-4GlcNAcb1-3Galb1-4GlcNAc",type:"lactosamine"},{name:"Lewis A",
sequence:"Galb1-3(Fuca1-4)GlcNAc",type:"lewis"},{name:"Lewis B",sequence:"Fuca1-2Galb1-3(Fuca1-4)GlcNAc",type:"lewis"},{name:"Lewis C",sequence:"Galb1-3GlcNAc",type:"lewis"},{name:"Lewis D",sequence:"Fuca1-2Galb1-3GlcNAc",type:"lewis"},{name:"Lewis X",sequence:"Galb1-4(Fuca1-3)GlcNAc",type:"lewis"},{name:"Lewis Y",sequence:"Fuca1-2Galb1-4(Fuca1-3)GlcNAc",type:"lewis"}],monos="Glc Man Gal Gul Alt All Tal Ido GlcNAc ManNAc GalNAc GulNAc AltNAc AllNAc TalNAc IdoNAc GlcN ManN GalN GulN AltN AllN TalN IdoN GlcA ManA GalA GulA AltA AllA TalA IdoA Qui Rha 6dGul 6dAlt 6dTal Fuc QuiNAc RhaNAc 6dAltNAc 6dTalNAc FucNAc Oli Tyv Abe Par Dig Col Ara Lyx Xyl Rib Kdn Neu5Ac Neu5Gc Neu Sia Pse Leg Aci 4eLeg Bac LDmanHep Kdo Dha DDmanHep MurNAc MurNGc Mur Api Fru Tag Sor Psi Hex HexN HexNAc".split(" "),
aminoacids="AGILPVFWYDERHKSTCMNQ".split(""),gctMonoList={Hex:{glycoct:"HEX",transform:"",configdefault:""},Glc:{glycoct:"glc-HEX",transform:"",configdefault:"d"},Man:{glycoct:"man-HEX",transform:"",configdefault:"d"},Gal:{glycoct:"gal-HEX",transform:"",configdefault:"d"},Gul:{glycoct:"gul-HEX",transform:"",configdefault:"d"},Alt:{glycoct:"alt-HEX",transform:"",configdefault:"l"},All:{glycoct:"all-HEX",transform:"",configdefault:"d"},Tal:{glycoct:"tal-HEX",transform:"",configdefault:"d"},Ara:{glycoct:"ara-PEN",
transform:"",configdefault:"l"},Lyx:{glycoct:"lyx-PEN",transform:"",configdefault:"d"},Rib:{glycoct:"rib-PEN",transform:"",configdefault:"d"},Bac:{glycoct:"glc-HEX",transform:"|2:d|4:d|6:d",configdefault:"d"},Fuc:{glycoct:"gal-HEX",transform:"-1:5|6:d",configdefault:"l"},HexA:{glycoct:"HEX",transform:"|6:a",configdefault:""},GlcA:{glycoct:"glc-HEX",transform:"-1:5|6:a",configdefault:"d"},ManA:{glycoct:"man-HEX",transform:"-1:5|6:a",configdefault:"d"},GalA:{glycoct:"gal-HEX",transform:"-1:5|6:a",configdefault:"d"},
GulA:{glycoct:"gul-HEX",transform:"-1:5|6:a",configdefault:"d"},AltA:{glycoct:"alt-HEX",transform:"-1:5|6:a",configdefault:"l"},AllA:{glycoct:"all-HEX",transform:"-1:5|6:a",configdefault:"d"},TalA:{glycoct:"tal-HEX",transform:"-1:5|6:a",configdefault:"d"},Qui:{glycoct:"glc-HEX",transform:"-1:5|6:d",configdefault:"d"},dHex:{glycoct:"HEX",transform:"|6:d",configdefault:""},Ido:{glycoct:"ido-HEX",transform:"",configdefault:"l"},IdoA:{glycoct:"ido-HEX",transform:"-1:5|6:a",configdefault:"l"},Pen:{glycoct:"PEN-1:4",
transform:"",configdefault:""},Rha:{glycoct:"man-HEX",transform:"|6:d",configdefault:"l"},SixdAlt:{glycoct:"alt-HEX",transform:"|6:d",configdefault:"l"},SixdTal:{glycoct:"tal-HEX",transform:"|6:d",configdefault:"d"},Xyl:{glycoct:"xyl-PEN",transform:"",configdefault:"d"},ddHex:{glycoct:"HEX",transform:"|2:d|6:d",configdefault:""},Unknown:{glycoct:"unknown",transform:"",configdefault:""},Oli:{glycoct:"PEN",transform:"|3:d|6:d",configdefault:""},Tyv:{glycoct:"ara-HEX",transform:"|3:d|6:d",configdefault:""},
Abe:{glycoct:"dxyl-HEX",transform:"|3:d|6:d",configdefault:""},Par:{glycoct:"rib-HEX",transform:"|3:d|6:d",configdefault:""},Col:{glycoct:"lxyl-HEX",transform:"|3:d|6:d",configdefault:""},Dig:{glycoct:"rib-HEX",transform:"|2:d|6:d",configdefault:"d"},Nonu:{glycoct:"NON",transform:"",configdefault:""},Kdn:{glycoct:"gro-dgal-NON-2:6",transform:"|1:a|2:keto|3:d",configdefault:"d"},Kdo:{glycoct:"man-OCT-2:6",transform:"|1:a|2:keto|3:d",configdefault:"d"},Fru:{glycoct:"ara-HEX-2:5",transform:"|2:keto",
configdefault:"d"},Assigned:{glycoct:"assigned-PEN",transform:"",configdefault:""},LDManHep:{glycoct:"ldmanhep-HEX",transform:"",configdefault:""},DDManHep:{glycoct:"ddmanhep-HEX",transform:"",configdefault:""},Dha:{glycoct:"dha-HEX",transform:"",configdefault:""},Mur:{glycoct:"mur-HEX",transform:"",configdefault:""},Sia:{glycoct:"sia-NON",transform:"",configdefault:""},Api:{glycoct:"api-PEN",transform:"",configdefault:"l"},Tag:{glycoct:"tag-PEN",transform:"",configdefault:"d"},Sor:{glycoct:"sor-PEN",
transform:"",configdefault:"l"},Psi:{glycoct:"psi-PEN",transform:"",configdefault:"d"}},gctSubList={NAcetyl:{glycoct:"n-acetyl"},Amino:{glycoct:"amino"},NGlycolyl:{glycoct:"n-glycolyl"},Methyl:{glycoct:"methyl"},Acetyl:{glycoct:"acetyl"},Sulfate:{glycoct:"sulfate"},Phosphate:{glycoct:"phosphate"},Bromo:{glycoct:"bromo"},Chloro:{glycoct:"chloro"},Ethyl:{glycoct:"ethyl"},Ethanolamine:{glycoct:"ethanolamine"},Fluoro:{glycoct:"fluoro"},Formyl:{glycoct:"formyl"},Hydroxymethyl:{glycoct:"hydroxymethyl"},
Imino:{glycoct:"imino"},RLactate1:{glycoct:"(r)-lactate"},SLactate1:{glycoct:"(s)-lactate"},NAlanine:{glycoct:"n-alanine"},NFormyl:{glycoct:"n-formyl"},NMethyl:{glycoct:"n-methyl"},NSuccinate:{glycoct:"n-succinate"},NSulfate:{glycoct:"n-sulfate"},NTrifluoroacetyl:{glycoct:"n-trifluoroacetyl"},Nitrate:{glycoct:"nitrate"},Pyruvate:{glycoct:"pyruvate"},Thio:{glycoct:"thio"},RPyruvate:{glycoct:"(r)-pyruvate"},SPyruvate:{glycoct:"(s)-pyruvate"},RLactate2:{glycoct:"(r)-lactate2"},SLactate2:{glycoct:"(s)-lactate2"},
Unknown:{glycoct:"unknown"}},commonMonos="Glc Man Gal GlcNAc GalNAc Fuc Neu5Ac Neu5Gc Neu Xyl IdoA GlcA Unknown".split(" "),getUrl=window.location.href.split("/").slice(0,-1).join("/")+"/",svgStyle="",fetchCSS=d3.text(getUrl+"/css/styles.css").then(function(a){svgStyle=a}),svgarr=[],fetchSVG=d3.xml("img/monos.svg").then(function(a){return svgarr=[].map.call(a.querySelectorAll("symbol"),function(c){return{id:c.getAttribute("data-abbr"),viewBox:c.getAttribute("viewBox"),innerhtml:c.innerHTML.replace(/\n|\t/g,
"").trim(),fullname:c.getAttribute("data-shortname")}})});function resetchildglycan(){childglycan={name:"",linkage:"",monosaccharide:"",linknum:0,substituent:"",children:[]};$("#subscheck").empty();$("#monocheck").empty();$("#linkagecheck").empty()}
function addSub(){var a=Array.from(document.querySelectorAll("#subposlist input"));a=a.length&&a.find(function(b){return b.checked}).value;var c=Array.from(document.querySelectorAll("#subtypelist input"));c=c.length&&c.find(function(b){return b.checked}).value;"other"===c&&(c=document.getElementById("substituentother").value);a="["+(a+c)+"]";$("#subscheck").append(a);childglycan.substituent+=a;makechildglycanname()}
function clearSub(){$("#subscheck").empty();childglycan.substituent="";makechildglycanname()}function monoselect(a){if("Unknown"===a&&(a=prompt("Please enter name for the node",""),null==a)){alert("Error: Name for the node was blank - did not add the node");return}childglycan.monosaccharide=a;$("#monocheck").empty().append(a);makechildglycanname()}
function addLinkage(){var a=Array.from(document.querySelectorAll("#orientlist input"));a=a.length&&a.find(function(d){return d.checked}).value;var c=Array.from(document.querySelectorAll("#anoposlist input"));c=c.length&&c.find(function(d){return d.checked}).value;var b=Array.from(document.querySelectorAll("#acclist input"));b=b.length&&b.find(function(d){return d.checked}).value;childglycan.linknum="?"==b?0:+b;a=a+c+"-"+b;$("#linkagecheck").empty().append(a);childglycan.linkage=a;makechildglycanname()}
function makechildglycanname(){childglycan.name=childglycan.substituent+childglycan.monosaccharide+childglycan.linkage}
function addmono(a,c){function b(f){if(f.name===a[e].data.name)if(e<a.length-1){e++;var g=f.children.findIndex(function(k){return k.name===a[e].data.name&&k.uniqueNodeID===a[e].data.uniqueNodeID});b(f.children[g])}else f.children.forEach(function(k){k.linknum==childglycan.linknum&&(h=!0,alert("You are trying to add a node to a position which is occupied. \nTwo nodes cannot have same linkage acceptor position. \nPlease check the linkages."))}),!1===h&&f.children.push(childglycan);return f}if(""==childglycan.monosaccharide)alert("No monosaccharide selected. \n\nPlease select a monosaccharide to add."),
resetchildglycan(),$("#multimode").empty();else{""===childglycan.linkage&&(childglycan.linkage="??-?");var d=document.getElementById(nameid).value;d=JSON.parse(glycantojson(d));var e=0,h=!1;b(d);outputname(d);!1===h&&0==c&&resetchildglycan()}}function outputname(a){a=d3.hierarchy(a);a=sortchildren(a);a=objecttoname(a);tracknames(a);document.getElementById(nameid).value=a;d3glycanstructure(a,{drawdivID:"d3glycanstruc"});cfgToGlycoCT()}
function addfirstmono(){nameobj=childglycan;if(""===nameobj.linkage){var a=prompt('You have not added any linkage for the first monosaccharide.\n    \nThis will be treated as an open ring. If this is what you desire leave the field below blank and press OK.\n    \nTo indicate a closed ring please type in the linkage information:\n    \nFor example:\n    \n"??" if linkage position is unknown in both anomeric configuratio and position or\n    \n"?1" where 1 indicates the position number and can be replaced with the position you desire.  or\n    \n"b1" where b indicates the anomeric configuration and 1 indicates the position.\n    ',
"");nameobj.linkage=null==a||""==a?"":a}else nameobj.linkage=nameobj.linkage.split(/\-/g)[0];nameobj.name=nameobj.substituent+nameobj.monosaccharide+nameobj.linkage;outputname(nameobj);resetchildglycan()}
function d3glycanstructure(a,c){var b={width:360,height:520,orientation:"bottom-to-top",drawdivID:"d3glycanstruc",symbsize:30,drawingareachoice:"fixglycansize",fucopt:"fucdown",linkageVisible:!0,linkRotate:!1,linkAbbr:!1,linkFontSize:16,margin:{top:50,right:50,bottom:50,left:50},drawingSettingsDivID:"drawsetting",userOverrideOptions:!0};if("undefined"!==typeof c)for(var d in c)"undefined"!==typeof c[d]&&(b[d]=c[d]);!0===b.userOverrideOptions&&(b=getUserDrawingOptions(b));if("right-to-left"===b.orientation){var e=
b.width;b.width=b.height;b.height=e}drawersize=400;!0===glyd3render&&($("#slideout").css("width",drawersize+"px"),$("#slideout").animate({right:"0px"},{queue:!1,duration:500}));e=glycantojson(a);var h=JSON.parse(e),f=getDepth(h),g=b.margin,k,m;"right-to-left"==b.orientation?k=b.height-g.top-g.bottom:m=b.width-g.left-g.right;"fixdrawingarea"===b.drawingareachoice?"right-to-left"==b.orientation?m=b.width-g.left-g.right:k=b.height-g.top-g.bottom:"fixglycansize"===b.drawingareachoice&&2>=f?"right-to-left"==
b.orientation?m=50*f:k=50*f:"fixglycansize"===b.drawingareachoice&&10>f?"right-to-left"==b.orientation?m=50*f:k=50*f:"fixglycansize"===b.drawingareachoice&&10<=f&&("right-to-left"==b.orientation?m=b.width-g.top-g.bottom:k=b.height-g.top-g.bottom);var q={"right-to-left":{size:[k,m],x:function(l){return m-l.y},y:function(l){return l.x}},"bottom-to-top":{size:[m,k],x:function(l){return l.x},y:function(l){return k-l.y}}};"d3glycanstruc"==b.drawdivID&&d3.select("#d3glycanstrucsub"+b.drawdivID).remove();
"bottom-to-top"===b.orientation?d3.select("#"+b.drawdivID).style("flex-direction","column-reverse"):d3.select("#"+b.drawdivID).style("flex-direction","row-reverse");d3.select("#"+b.drawdivID).append("div").attr("id","d3glycanstrucsub"+b.drawdivID);e=d3.select("#d3glycanstrucsub"+b.drawdivID).append("svg").attr("id",b.drawdivID+"SVG").attr("width",m+g.left+g.right).attr("height",k+g.top+g.bottom).append("g").attr("id","glycang").attr("transform","translate("+g.left+","+g.top+")");var u=q[b.orientation];
q=d3.tree().size(u.size);var t=d3.hierarchy(h);"right-to-left"==b.orientation&&(t=sortchildren(t,!0));t=q(t);fixfucers(t,b);"right-to-left"==b.orientation?(h=t.x-k/2,0!=h&&(10>f?d3.select("#glycang").attr("transform","translate("+(m+g.left-50*f)+","+(g.top-h)+")"):d3.select("#glycang").attr("transform","translate("+g.left+","+(g.top-h)+")"))):(h=t.x-m/2,0!=h&&d3.select("#glycang").attr("transform","translate("+(g.left-h)+","+g.top+")"));f=t.descendants().slice(1);e.selectAll(".glyd3link").data(f).enter().append("path").attr("class",
"glyd3link").attr("d",function(l){return"M"+u.x(l)+","+u.y(l)+"L"+u.x(l.parent)+","+u.y(l.parent)}).attr("stroke-width",2);e=e.selectAll(".node").data(t.descendants()).enter().append("g").attr("transform",function(l){return rotateFuc(l,u,b)});e.append("use").attr("xlink:href",function(l,n){return drawsymbol(l,n,"glycan")}).attr("x",-b.symbsize/2).attr("y",-b.symbsize/2).attr("height",b.symbsize).attr("width",b.symbsize).attr("class","symbol").on("click",function(l){l=t.path(l);var n=Array.from(document.querySelectorAll("#modelist input"));
n=n.length&&n.find(function(r){return r.checked}).value;"add"===n?multimode?addmono(l,!0):addmono(l,!1):"replace"===n?multimode?replacemono(l,!0):replacemono(l,!1):"delete"===n&&deletemono(l)}).on("mouseover",function(l){d3.select(this.parentElement).append("circle").attr("class","highlightnode").attr("r",b.symbsize/2+10).attr("fill",function(n){n=Array.from(document.querySelectorAll("#modelist input"));n=n.length&&n.find(function(r){return r.checked}).value;if("add"===n)return d3.select(this.parentElement).selectAll(".symbol").classed("addcursor",
!0).classed("replacecursor",!1).classed("deletecursor",!1),"#227093";if("replace"===n)return d3.select(this.parentElement).selectAll(".symbol").classed("replacecursor",!0).classed("addcursor",!1).classed("deletecursor",!1),"#FFBA3B";if("delete"===n)return d3.select(this.parentElement).selectAll(".symbol").classed("deletecursor",!0).classed("addcursor",!1).classed("replacecursor",!1),"#7D1515"}).attr("fill-opacity",.4).lower();$(document).bind("keyup",function(n){"Delete"!=n.originalEvent.key&&"d"!=
n.originalEvent.key||$.when($(document).unbind("keyup")).then(function(r){r=t.path(l);deletemono(r)})})}).on("mouseout",function(l){$(document).unbind("keyup");d3.selectAll(".highlightnode").remove()});!0===b.linkageVisible&&e.append("text").attr("transform",function(l,n){return transformlinkText(l,n,b)}).text(function(l){return linkageText(l,d,b)}).attr("font-size",b.linkFontSize).attr("text-anchor","middle").style("font-family","Arial,Sans");e=e.append("text").text(function(l){return subText(l)}).attr("font-size",
b.linkFontSize).style("font-family","Arial,Sans");"bottom-to-top"===b.orientation?e.attr("x",-b.linkFontSize-3).attr("y",3).attr("text-anchor","end"):e.attr("x",3).attr("y",b.linkFontSize+b.symbsize/2).attr("text-anchor","middle")}
function getUserDrawingOptions(a){var c=document.querySelector("#"+a.drawingSettingsDivID+" form");if(!c)return console.warn("GlycoGlyph: No settings div found, using default options."),a;c.querySelectorAll("input, select, checkbox").forEach(function(b){a[b.id]="checkbox"===b.type?b.checked:"number"===b.type?+b.value:b.value});return a}function getDepth(a){var c=0;a.children&&a.children.forEach(function(b){b=getDepth(b);b>c&&(c=b)});return 1+c}
function fixfucers(a,c){if("fucoriginal"!==c.fucopt){var b=c.width-c.margin.left-c.margin.right;"right-to-left"===c.orientation&&(b=c.height-c.margin.top-c.margin.bottom);var d=a.x;a.each(function(e){if("Fuc"===e.data.monosaccharide&&0!==e.depth){e.parent.children.filter(function(g){return-1===g.data.name.search("Fuc")});e.y=e.parent.y;var h=e.parent.x;"fucout"===c.fucopt&&(e.x=e.x<d?e.parent.x-b/5:e.x>d?e.parent.x+b/5:e.x==d?e.parent.x<d?e.parent.x-b/5:e.parent.x>d?e.parent.x+b/5:e.parent.x-b/5:
e.parent.x-b/5);"fucdown"===c.fucopt&&(e.x=e.x<e.parent.x?e.parent.x-b/5:e.parent.x+b/5);"fucleft"===c.fucopt&&(e.x=e.parent.x-b/5);var f;e.parent.children.forEach(function(g){"Fuc"!==g.data.monosaccharide&&void 0==f&&(f=g.x-h)});e.parent.children.forEach(function(g,k){"Fuc"!==g.data.monosaccharide&&g.data.name!==e.parent.data.name&&g.each(function(m){m.x-=f})})}})}}
function transformlinkText(a,c,b){if(0<c){c=180*Math.atan2(a.y-a.parent.y,a.parent.x-a.x)/Math.PI;if("right-to-left"===b.orientation){var d;if("Fuc"===a.data.monosaccharide&&"fucoriginal"!=b.fuctype)return 45>=c?"translate("+((a.y-a.parent.y)/2+b.linkFontSize/2)+","+(a.parent.x-a.x)/2+") rotate(90)":"translate("+((a.y-a.parent.y)/2-b.linkFontSize/2)+","+(a.parent.x-a.x)/2+") rotate(-90)";if(0==b.linkRotate)switch(!0){case a.x<a.parent.x:return"translate("+((a.y-a.parent.y)/2+b.linkFontSize)+","+((a.parent.x-
a.x)/2-b.linkFontSize)+")";case a.x===a.parent.x:return"translate("+(a.y-a.parent.y)/2+","+((a.parent.x-a.x)/2-b.linkFontSize/2)+")";case a.x>a.parent.x:return"translate("+((a.y-a.parent.y)/2+b.linkFontSize)+","+((a.parent.x-a.x)/2+b.linkFontSize)+")"}c=180*Math.atan2(a.parent.x-a.x,a.y-a.parent.y)/Math.PI;return"translate("+(a.y-a.parent.y)/2+","+((a.parent.x-a.x)/2-b.linkFontSize/2)+") rotate("+c+")"}"Fuc"===a.data.monosaccharide&&"fucoriginal"!=b.fuctype&&0<a.depth&&(c=a.x<a.parent.x?30:150);if("Fuc"===
a.data.monosaccharide&&"fucoriginal"!=b.fuctype)return 45>=c?"translate("+(a.parent.x-a.x-10)/2+","+(a.y-a.parent.y+25)/2+") rotate("+c+")":"translate("+(a.parent.x-a.x+10)/2+","+(a.y-a.parent.y+30)/2+") rotate(-30)";if(0==b.linkRotate)switch(b.linkAbbr?d=2:d=4,!0){case a.x<a.parent.x:return"translate("+(a.parent.x-a.x-6*b.linkFontSize+b.linkFontSize*d)/(b.linkFontSize/2)+","+(a.y-a.parent.y+5)/2+")";case a.x===a.parent.x:return"translate("+(a.parent.x-a.x+6*b.linkFontSize+b.linkFontSize*d)/(b.linkFontSize/
2)+","+(a.y-a.parent.y+5)/2+")";case a.x>a.parent.x:return"translate("+(a.parent.x-a.x+6*b.linkFontSize-b.linkFontSize*d)/(b.linkFontSize/2)+","+(a.y-a.parent.y+5)/2+")"}return"translate("+(a.parent.x+10-a.x)/2+","+(a.y-a.parent.y)/2+") rotate("+c+")"}return"translate("+b.symbsize/4+","+b.symbsize+")"}
function rotateFuc(a,c,b){if(0===a.depth||"right-to-left"===b.orientation||"fucoriginal"===b.fuctype||"Fuc"!==a.data.monosaccharide)return"translate("+c.x(a)+","+c.y(a)+")";a.y+=4;return a.x<a.parent.x?"translate("+c.x(a)+","+c.y(a)+") rotate(-30)":"translate("+c.x(a)+","+c.y(a)+") rotate(30)"}function drawsymbol(a,c,b){if("gp"!==b||0!==c)return a=void 0!=a.data.monosaccharide?a.data.monosaccharide:a.data.name,""!=a?"img/monos.svg#"+a.toLowerCase():"img/monos.svg#unknown"}
function linkageText(a,c,b){var d=a.data.linkage;if(""!=d){if(0===c)return d=d.replace("a","\u03b1").replace("b","\u03b2");c=b.linkAbbr;return"bottom-to-top"===b.orientation&&"Fuc"===a.data.monosaccharide&&a.x>a.parent.x?(1==c&&(d=d.replace(/[\d\?]\-/g,"")),d=d.split("").reverse().join(""),d=d.replace(/a/gi,"\u03b1").replace(/b/gi,"\u03b2")):1==c?d=d.replace(/a(?=[\d\?]\-[\d\?])/g,"\u03b1").replace(/b(?=[\d\?]\-[\d\?])/,"\u03b2").replace(/[\d\?]\-/g,""):-1<d.search(/[a,b,\?][\d,\?]\-[\d,\?]/)?(-1<
d.search(/a[\d,\?]\-[\d,\?]/)?d=d.replace(/a(?=[\d\?]\-[\d\?])/,"\u03b1"):-1<d.search(/b[\d\?]\-[\d\?]/)&&(d=d.replace(/b(?=[\d\?]\-[\d\?])/,"\u03b2")),d.substr(d.indexOf("-")-2)):-1<d.search(/[a,b,\?]\-/)?d.substr(d.indexOf("-")-1):-1<d.search(/[a,b,\?][\d,\?]/)?"a"===d.charAt(d.length-2)?"\u03b1"+d.charAt(d.length-1):"b"===d.charAt(d.length-2)?"\u03b2"+d.charAt(d.length-1):d:"a"===d?"\u03b1":"b"===d?"\u03b2":d}}
function subText(a){if(void 0!=a.data.substituent)return a=a.data.substituent,a=a.replace(/\[(?=[0-9a-zA-Z])/g,"").replace(/\](?=[0-9a-zA-Z])/g,",").replace("]","")}
function deletemono(a){function c(e){if(e.name===a[d].data.name)if(d<a.length-2){d++;var h=e.children.findIndex(function(f){return f.name===a[d].data.name&&f.uniqueNodeID===a[d].data.uniqueNodeID});c(e.children[h])}else h=e.children.findIndex(function(f){return f.name===a[d+1].data.name&&f.uniqueNodeID===a[d+1].data.uniqueNodeID}),e.children.splice(h,1);return e}if(1==a.length)document.getElementById(nameid).value="",$("#d3glycanstruc").empty(),$("#glycoCT").html("");else{var b=document.getElementById(nameid).value;
b=JSON.parse(glycantojson(b));var d=0;c(b);outputname(b);resetchildglycan()}}
function getGTCID(){function a(h){return""!=h.monosaccharide?h:a(h.children[0])}var c=[{anomer:"a",name:"alpha"},{anomer:"b",name:"beta"},{anomer:"?",name:"unknown"},{anomer:"",name:"open"}];$("#gtcid").html('\n    <table class="table table-sm">\n      <thead>\n        <tr>\n          <th>Reducing End Type:</th>\n          <th class="alpha" scope="col">&alpha;</th>\n          <th class="beta" scope="col">&beta;</th>\n          <th class="unknown" scope="col">Unknown (?)</th>\n          <th class="open"  scope="col">Open</th>\n        </tr>\n      </thead>\n      <tbody>\n        <tr>\n          <td>GlyTouCan ID:</th>\n          <td class="alpha" id="alphagtcid"></td>\n          <td class="beta" id="betagtcid"></td>\n          <td class="unknown" id="unknowngtcid"></td>\n          <td class="open" id="opengtcid"></td>\n        </tr>\n        <tr>\n          <td>View Details:</th>\n          <td class="alpha" id="alphadetails"></td>\n          <td class="beta" id="betadetails"></td>\n          <td class="unknown" id="unknowndetails"></td>\n          <td class="open" id="opendetails"></td>\n      </tr>\n      </tbody>\n    </table>\n    ');var b=
document.getElementById(nameid).value,d=JSON.parse(glycantojson(b));d=a(d);if(""!==d.monosaccharide)var e=d.anomer;c.forEach(function(h){d.anomer=h.anomer;var f=JSON.stringify(d);f=jsonToGlycoCT(f);f="https://api.glycosmos.org/glycanformatconverter/2.3.2-snapshot/glycoct2wurcs/"+encodeURI(f);$.get(f).done(function(g){void 0===g.id?($("#"+h.name+"gtcid").html("Error in Structure"),console.log(g)):"no accnumber"===g.id?($("#"+h.name+"gtcid").html("Not Available"),console.log(g)):($("#"+h.name+"gtcid").html(""+
g.id),$.get("https://api.glygen.org/glycan/detail/"+g.id+"/").done(function(k){$("#"+h.name+"details").append('\n            <a href="https://www.glygen.org/glycan/'+g.id+'" target="_blank"\n            title="View in GlyGen">\n            <span class="glygen-logo detail-icon"></span></a>\n            <a href="https://glytoucan.org/Structures/Glycans/'+g.id+'" target="_blank"\n            title="View in GlyTouCan">\n            <span class="glytoucan-logo detail-icon"></span></a>');if(k.crossref){var m=
k.crossref.find(function(q){return"PubChem Compound"===q.database});m&&$("#"+h.name+"details").append('\n              <a href="'+m.url+'" target="_blank"\n              title="View in PubChem">\n              <span class="pubchem-logo detail-icon"></span></a>');(k=k.crossref.find(function(q){return"ChEBI"===q.database}))&&$("#"+h.name+"details").append('\n              <a href="'+k.url+'" target="_blank"\n              title="View in ChEBI">\n              <span class="chebi-logo detail-icon"></span></a>')}}).fail(function(k){k.responseJSON.error_list.some(function(m){return"non-existent-record"===
m.error_code})?console.log("GlyTouCan ID does not exist in glygen"):(console.log("Failed to connect to GlyGen"),console.log(k));$("#"+h.name+"details").append('\n          <span class="glygen-logo detail-icon disabled-icon"></span>\n          <a href="https://glytoucan.org/Structures/Glycans/'+g.id+'" target="_blank"\n            title="View in GlyTouCan">\n            <span class="glytoucan-logo detail-icon"></span></a>\n          ')}))}).fail(function(){alert("Error communicating with GlyTouCan.")}).done(function(){c.filter(function(g){return g.anomer===
e}).forEach(function(g){d3.selectAll("."+g.name).classed("table-success",!0)})})})}
function glycantojson(a){a=a.replace(/ /g,"");a=a.replace(/\((?=\d[a-zA-Z]\))/g,"[");a=a.replace(/(\[\d[a-zA-Z])\)/g,"$1]");-1<a.indexOf("GlcN(Gc)")&&(a=a.replace(/GlcN\(Gc\)/,"GlcNGc"));a=function(c){c=c.split(/(\)|\(|-[\d,\?]|-(?=[a-zA-z]))/g).filter(function(d){return""!==d});var b=[];for(i=0;i<c.length-1;i++)-1<c[i+1].search(/\-[\d,\?]/)?b.push(c[i]+c[i+1]):0>c[i].search(/\-/)&&b.push(c[i]);b.push(c[c.length-1]);return b}(a);return JSON.stringify(a.reduce(function(c,b,d,e){e=c.lastIndexOf("(");
if("("===b)c.push(b);else if(")"===b)c.splice(e,1);else if("-"!==b){var h,f=b.substring(b.lastIndexOf("]")+1,b.length);f!=b&&(h=b.replace(f,""));for(i=0;i<f.length;i++)if(!0===monos.includes(f.substring(0,f.length-i))){var g=f.substring(f.length-i,f.length);var k=+g.substr(-1);var m=f.substring(0,f.length-i);break}-1<b.search(/Neu5,9Ac2?/g)&&(m="Neu5Ac",h="[9Ac]",g=b.replace(/Neu5,9Ac2?/g,""),k=+g.substr(-1));void 0==g&&(g="");void 0==m&&(m="");void 0==h&&(h="");void 0==k&&(k=0);f=g.charAt(0);/^\d+$/.test(f)&&
(f="?");/\-$/.test(g)&&(g=g.replace(/\-$/,""));c.push({name:b,linkage:g,monosaccharide:m,substituent:h,linknum:k,anomer:f,uniqueNodeID:d,children:c.splice(e+1,c.length-e-1).reverse()})}return c},[])[0],0,2)}function cfgToGlycoCT(){var a=document.getElementById(nameid).value;""===a?alert("No name typed. Please check Name above."):(a=glycantojson(a),a=jsonToGlycoCT(a).replace(/\n/g,"<br>"),document.getElementById("glycoCT").innerHTML=a)}
function jsonToGlycoCT(a){function c(g,k){k=void 0===k?1:k;var m=g.data,q=m.monosaccharide,u=0,t=e,l=splitSubs(m.substituent).pop(),n="";n=void 0==m.anomer?"x":""===m.anomer||"-"===m.anomer?"o":"?"==m.anomer?"x":m.anomer;var r="";-1<q.indexOf("NAc")?(r=q.split("NAc")[0],l.unshift("NAc"),u++):-1<q.indexOf("NGc")?(r=q.split("NGc")[0],l.unshift("NGc"),u++):"Neu5Ac"===q?(r="Kdn",l.unshift("5Ac"),u++):"Neu5Gc"===q?(r="Kdn",l.unshift("5Gc"),u++):-1<q.indexOf("N")&&gctMonoList.hasOwnProperty(q.replace(/N/g,
""))?(r=q.replace(/N/g,""),l.unshift("N"),u++):r=q;var w=getRingType(q,n);gctMonoList.hasOwnProperty(r)&&(""==gctMonoList[r].transform?(d+=e+"b:"+n+"-"+gctMonoList[r].configdefault+gctMonoList[r].glycoct+"-"+w+gctMonoList[r].transform,"o"===n&&(d+="|1:aldi")):d+=e+"b:"+n+"-"+gctMonoList[r].configdefault+gctMonoList[r].glycoct+gctMonoList[r].transform,d+="\n",e++);""!==m.linkage&&"?"!==m.linkage&&1!=f&&(n=m.linkage,m=n.charAt(n.length-1),n=n.charAt(n.indexOf("-")-1),"?"===m&&(m="-1"),"?"===n&&(n="1"),
h+=f+":"+k+"o("+m+"+"+n+")"+t+"d\n",f++);l=l.filter(function(p){return""!==p});l.forEach(function(p){switch(!0){case "NAc"===p:var v=2;p="n-acetyl";break;case "NGc"===p:v=2;p="n-glycolyl";break;case -1<p.indexOf("Ac"):v=p.split(/(?!\d)/g)[0];p="acetyl";"Neu5Ac"===q&&5==v&&(p="n-acetyl");break;case -1<p.indexOf("Gc"):v=p.split(/(?!\d)/g)[0];p="glycolyl";"Neu5Gc"===q&&(p="n-glycolyl");break;case -1<p.indexOf("Me"):v=p.split(/(?!\d)/g)[0];p="methyl";break;case -1<p.indexOf("N"):v=2;p="amino";break;case -1<
p.indexOf("S"):v=p.split(/(?!\d)/g)[0];p="sulfate";break;case -1<p.indexOf("P"):v=p.split(/(?!\d)/g)[0];p="phospho";break;default:v=p.charAt(0),p=p.split(/(?!\d)/g)[1]}d+=e+"s:"+p+"\n";h+=f+":"+t+"d("+v+"+1)"+e+"n\n";f++;u++;e++});0<g.data.children.length&&g.children.forEach(function(p){return c(p,t)});return g}var b="Hello";a=JSON.parse(a);a=d3.hierarchy(a);var d="RES\n",e=1,h="LIN\n",f=1;c(a);return b=("LIN\n"!==h?d+h:d).trim()}
function splitSubs(a){if(""===c)return[];var c=a.replace(/\[(?=[0-9a-zA-Z])/g,"").replace(/\](?=[0-9a-zA-Z])/g,",").replace("]","");c=c.split(/,/g);"object"===typeof c&&(c=[c]);return c}function getRingType(a,c){if("o"===c)return"0:0";var b="Rib,Api,Ara";var d="Gal,Glc,Man,GalNAc,GlcNAc,ManNAc,Fuc,Neu5Ac,Neu5Gc,Neu,Sia,Xyl,IdoA,GlcA,\n  GalA,GlcA,ManA,GlcN,GalN,ManN,Hex,HexNAc,HexA,HexN\n  ".split(/,/g);b=b.split(/,/g);return d.includes(a)?"1:5":b.includes(a)?"1:4":"x:x"}
function copyGlycoCT(a){if(document.selection){var c=document.body.createTextRange();c.moveToElementText(document.getElementById(a));c.select().createTextRange();document.execCommand("copy")}else window.getSelection&&(c=document.createRange(),c.selectNode(document.getElementById(a)),window.getSelection().addRange(c),document.execCommand("copy"),alert("GlycoCT Copied"))}
fetchSVG.then(function(a){svgarr.forEach(function(c){appendButton(c,"fulllist")});commonMonos.forEach(function(c){var b=svgarr.find(function(d){return d.id==c});appendButton(b,"commonlist")})});
function appendButton(a,c){var b=d3.select("#"+c).append("div").attr("class","monodiv").append("div").attr("id",c+"btn"+a.id).attr("class","monobtndiv").attr("title",a.id+" OR "+a.fullname).attr("data-abbr",a.id).on("mouseup",function(){monoselect(this.dataset.abbr)}).append("svg").attr("id","mono"+a.id).attr("viewBox",a.viewBox).attr("xmlns","http://www.w3.org/2000/svg").attr("width","55").attr("height","35");b.append("g").attr("transform","scale(0.5 0.5) translate(25,0)").html(a.innerhtml);b.append("g").attr("transform",
"translate(50%,50)").append("text").text(a.id).attr("text-anchor","middle").attr("x","50%").attr("y","90%").attr("font-size","1em")}function appendTerminals(){terminals.forEach(function(a,c){$("#terminalslist").append('\n    <li class="template">\n    <button class="btn btn-outline-primary btn-sm"\n      onclick="addTerminaltoChild('+c+')">'+a.name+"</button>\n    </li>\n  ")})}
function addTerminaltoChild(a){a=terminals[a].sequence;childglycan=JSON.parse(glycantojson(a));$("#monocheck").html(a);$("#linkagecheck").html("<i>Add Linkage</i>")}var bracketcount=0;
function objecttoname(a,c){var b="";if(""!=a.data.monosaccharide&&""!=a.data.linkage){if(void 0===a.data.substituent||"[]"===a.data.substituent)a.data.substituent="";a.data.linkage&&-1===a.data.linkage.search("-")&&0<a.depth&&(a.data.linkage+="-");b=a.data.substituent+a.data.monosaccharide+a.data.linkage+b}else b=""==a.data.linkage&&null==a.parent?a.data.name+b:a.data.name+"-"+b;1<c&&(b+=")");a.data.children&&0<a.data.children.length&&a.children.forEach(function(d,e){b=objecttoname(d,a.children.length-
e)+b});1<c&&(b="("+b);return b}
function replacemono(a,c){function b(h){if(h.name===a[e].data.name)if(e<a.length-2){e++;var f=h.children.findIndex(function(k){return k.name===a[e].data.name&&k.uniqueNodeID===a[e].data.uniqueNodeID});b(h.children[f])}else{f=h.children.findIndex(function(k){return k.name===a[e+1].data.name});if(""!=childglycan.linkage){var g=h.children.findIndex(function(k){return k.linknum===childglycan.linknum});if(-1<g&&g!=f){alert("Two nodes cannot have same linkage position. Please check linkages.");return}h.children[f].linkage=
childglycan.linkage;h.children[f].linknum=childglycan.linknum}""!=childglycan.monosaccharide&&(h.children[f].monosaccharide=childglycan.monosaccharide);""!=childglycan.substituent?h.children[f].substituent=childglycan.substituent:"[]"==childglycan.substituent&&(h.children[f].substituent="");h.children[f].name=h.children[f].substituent+h.children[f].monosaccharide+h.children[f].linkage}return h}if(1==a.length)outputname(childglycan),resetchildglycan();else if(""==childglycan.monosaccharide&&""==childglycan.linkage&&
""==childglycan.substituent)alert("No replacement criteria selected. Please select what would you like to replace with.");else{var d=document.getElementById(nameid).value;d=JSON.parse(glycantojson(d));var e=0;b(d);outputname(d);!1===c&&resetchildglycan()}}
function replacecss(a){svgStyle.replace(/\/\*.*\*\//g,"").replace(/\r?\n|\r/g,"").split("}").forEach(function(c){if(""!=c.trim()){c=c.split("{");var b=c[0].trim();c[1].split(";").forEach(function(d){if(""!=d.trim()){d=d.split(":");var e=d[0].trim(),h=d[1].trim();"font-weight"==e?d3.select("#"+a).selectAll(b).each(function(f,g){this.getAttribute(e)||this.style[e]===h||d3.select(this).style(e+"",h+"")}):d3.select("#"+a).selectAll(b).each(function(f,g){this.getAttribute(e)||this.style[e]||d3.select(this).style(e+
"",h+"")})}})}})}function replaceuse(a){$("#"+a+" use").each(function(c){c=this.getAttribute("href");if(null!==c){var b=c.split("#")[1],d=this.getAttribute("x"),e=this.getAttribute("y"),h=this.getAttribute("height"),f=this.getAttribute("width");c=svgarr.find(function(g){return g.id.toLowerCase()==b});d='<svg id="'+b+'" x="'+d+'" y="'+e+'" height="'+h+'" width="'+f+'" viewBox="'+c.viewBox+'">';d+=c.innerhtml;d+="</svg>";$(this).parent().prepend(d)}}).remove()}
function savesvg(a){replacecss(a);replaceuse(a);var c=document.getElementById(a);c.setAttribute("xmlns","http://www.w3.org/2000/svg");c.setAttribute("xmlns:xlink","http://www.w3.org/1999/xlink");c=document.getElementById(a).outerHTML;a=new Blob([c],{type:"image/svg+xml;charset=utf-8"});a=URL.createObjectURL(a);c=document.createElement("a");c.href=a;c.download="Figure.svg";document.body.appendChild(c);c.click();document.body.removeChild(c);d3glycanstructure(document.getElementById(nameid).value,{drawdivID:"d3glycanstruc"})}
function sortchildren(a,c){c=void 0===c?!1:c;a.children&&0<a.data.children.length&&(c?a.children.sort(function(b,d){return d3.descending(b.data.linknum,d.data.linknum)}):a.children.sort(function(b,d){return d3.ascending(b.data.linknum,d.data.linknum)}),-1<a.children.findIndex(function(b){return"Fuc"==b.data.monosaccharide})&&1>=a.depth&&"GlcNAc"===a.data.monosaccharide&&-1<a.children.findIndex(function(b){return"GlcNAc"==b.data.monosaccharide})&&a.children.sort(function(b,d){return"Fuc"==b.data.monosaccharide?
-1:"Fuc"==d.data.monosaccharide?1:0}),a.children.forEach(function(b){sortchildren(b,c)}));return a}function starttemplate(a){var c=document.getElementById(nameid);if(""==c.value||confirm("This will clear current Name field. Are you sure you would like to continue?")){c.value="";var b=templates.filter(function(d){return d.name==a&&"starter"===d.type});c.value=b[0].structure;tracknames(c.value);d3glycanstructure(c.value,{drawdivID:"d3glycanstruc"});cfgToGlycoCT()}}
function tracknames(a){0<tracknum&&$("#undodiv").removeClass("hide").addClass("show");trackname[tracknum]=a;tracknum++;trackname=trackname.filter(function(c,b){return b<tracknum});tracknum===trackname.length&&$("#redodiv").addClass("hide").removeClass("show")}
function undo(){if(!(2>tracknum)){var a=document.getElementById(nameid);tracknum--;void 0!=trackname[tracknum-1]&&(a.value=trackname[tracknum-1],""!=a.value?d3glycanstructure(a.value,{drawdivID:"d3glycanstruc"}):$("#d3glycanstruc").empty());1===tracknum&&$("#undodiv").addClass("hide").removeClass("show");tracknum<trackname.length&&$("#redodiv").removeClass("hide").addClass("show")}}
function redo(){if(!(tracknum>=trackname.length)){var a=document.getElementById(nameid);tracknum++;tracknum<=trackname.length&&(a.value=trackname[tracknum-1],""!=a.value?d3glycanstructure(a.value,{drawdivID:"d3glycanstruc"}):$("#d3glycanstruc").empty());tracknum===trackname.length&&$("#redodiv").addClass("hide").removeClass("show");tracknum<trackname.length&&$("#undodiv").removeClass("hide").addClass("show")}};